import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  en: {
    // Brand & Header
    announcement: '🇮🇳 Crafted in India • ✈️ Express Worldwide Delivery to 190+ Countries • Duties & Taxes Handled • Code',
    languageName: 'English (US)',
    currency: 'INR (₹)',
    home: 'HOME',
    shopAll: 'SHOP ALL',
    collections: 'COLLECTIONS',
    about: 'ABOUT',
    search: 'Search collection',
    bag: 'Shopping Bag',
    wishlist: 'Wishlist',
    signIn: 'Sign In',
    register: 'Create Account',
    account: 'Account Details',
    orderHistory: 'Order History',
    savedPieces: 'Saved Pieces',
    signOut: 'Sign Out',
    adminConsole: 'Admin Console',

    // Hero & Home
    heroTag: 'INDIA HERITAGE CRAFT • DISPATCHED WORLDWIDE TO 190+ COUNTRIES',
    heroTitle: 'ENGINEERED LUXURY ACROSS EVERY HORIZON',
    heroSubtitle: 'Directly sourced from India\'s master artisan guilds and modern tech laboratories—delivering to discerning clientele worldwide with express air transit.',
    shopCollection: 'Explore All Departments',
    exploreArrivals: 'Discover Flagships',
    scrollPrompt: 'Scroll to Discover',
    
    // Marquee
    marquee1: 'CRAFTED IN INDIA\'S MASTER ATELIERS',
    marquee2: 'COMPLIMENTARY WORLDWIDE EXPRESS OVER ₹10,000 / $120',
    marquee3: 'KASHMIR PASHMINA & VARANASI CHARMEUSE SILK',
    marquee4: 'DISPATCHING TO 190+ COUNTRIES WORLDWIDE',
    marquee5: 'KANNAUJ BOTANICAL EXTRAITS & SANDALWOOD ELIXIRS',
    marquee6: 'PRE-CALCULATED INTERNATIONAL DUTIES & ZERO SURPRISES',

    // Pillars
    signaturePillars: 'CURATED DEPARTMENTS',
    seasonalCurations: 'Department Pavilions',
    explorePillar: 'Explore Department',
    newReleases: 'FLAGSHIP RELEASES',
    justArrived: 'Latest Arrivals',
    viewAllNew: 'View All Products',

    // Split Editorial
    atelierStandard: 'The Master Standard',
    editorialTitle: 'EXCELLENCE IN EVERY DISCIPLINE',
    manifestoBtn: 'Read Brand Story',
    atelierParagraph1: 'We bridge futuristic engineering with artisanal luxury. Every product is selected for extraordinary permanence—from 3nm titanium smartphones and beryllium acoustic drivers to pure Sandalwood extraits and Roman travertine marble.',
    atelierParagraph2: 'Designed for discerning tastemakers who demand absolute perfection in technology, lifestyle, home ambiance, and sartorial expression.',
    editionFabricFocus: 'Curated Flagship Pavilion',
    curatedFavorites: 'Curated Favorites',
    trendingNow: 'TRENDING NOW',
    ethicallySourcedFibers: 'Handcrafted in India\'s Heritage Guilds',
    complimentaryExpressShipping: 'Worldwide Express Air Dispatch (190+ Countries)',
    complimentary30DayReturns: 'All Global Duties & VAT Pre-Calculated',
    outerwearVaultTitle: 'THE QUANTUM TECH PAVILION',
    outerwearVaultSubtitle: 'Grade 5 Titanium smartphones & tandem OLEDs',
    fineCashmereTitle: 'ACOUSTICS & HOROLOGY CHAMBER',
    fineCashmereSubtitle: 'Beryllium ANC headphones & sapphire smartwatches',
    relaxedTailoringTitle: 'FOOTWEAR & SNEAKER LAB',
    relaxedTailoringSubtitle: 'Civitanova Italian sneakers & Goodyear-welted boots',

    // Shop Catalog
    collectionTitle: 'THE MASTER CATALOG',
    refineCatalog: 'Filters & Refine',
    searchProducts: 'Search Products',
    categories: 'Departments',
    allSilhouettes: 'All Products',
    sizes: 'Sizes & Capacities',
    palette: 'Colors & Finishes',
    priceRange: 'Price Range',
    inStockOnly: 'In Stock Only',
    resetFilters: 'Reset All Filters',
    showing: 'Showing',
    pieces: 'Products',
    sortBy: 'Sort By',
    featured: 'Featured Curations',
    newest: 'Newest Releases',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',

    // Product Detail
    addToBag: 'Add To Shopping Bag',
    addingToBag: 'Adding...',
    soldOut: 'Sold Out',
    quickAdd: 'Quick Add',
    color: 'Color',
    selectSize: 'Select Size',
    sizeGuide: 'Size Guide',
    craftDetails: 'Craft & Details',
    materialsCare: 'Materials & Care',
    shippingReturns: 'Shipping & Returns',
    complimentaryDelivery: 'Complimentary Express Delivery',
    freeReturns: '30-Day Free Returns',
    coordinatingPieces: 'Coordinating Pieces',

    // Bag & Checkout
    bagEmpty: 'Your shopping bag is empty',
    discoverCollection: 'Discover The Collection',
    proceedCheckout: 'Proceed To Checkout',
    viewShoppingBag: 'View Shopping Bag',
    subtotal: 'Subtotal',
    discount: 'Discount',
    shipping: 'Shipping',
    totalDue: 'Total Due',
    complimentary: 'COMPLIMENTARY',
    promoCode: 'Promo Code',
    apply: 'Apply',
    finalizeAcquisition: 'Secure Checkout',
    contactDetails: '1. Contact Details',
    shippingAddress: '2. Shipping Address',
    paymentMethod: '3. Payment Method',
    confirmAuthorize: 'Confirm & Place Order',
    orderConfirmed: 'ORDER CONFIRMED',
    thankYou: 'Thank you for your purchase. We are preparing your order for shipment.',
  },
  es: {
    announcement: 'Envío exprés gratuito en pedidos superiores a ₹10,000 • Código',
    languageName: 'Español',
    currency: 'INR (₹)',
    home: 'INICIO',
    shopAll: 'TIENDA',
    collections: 'COLECCIONES',
    about: 'NOSOTROS',
    search: 'Buscar en la colección',
    bag: 'Bolsa de Compras',
    wishlist: 'Lista de Deseos',
    signIn: 'Iniciar Sesión',
    register: 'Crear Cuenta',
    account: 'Detalles de la Cuenta',
    orderHistory: 'Historial de Pedidos',
    savedPieces: 'Prendas Guardadas',
    signOut: 'Cerrar Sesión',
    adminConsole: 'Panel de Administrador',
    heroTag: 'COLECCIÓN N° 04 / EDICIÓN 2026',
    heroTitle: 'DEFINIDO POR EL DISEÑO',
    heroSubtitle: 'Prendas esenciales contemporáneas diseñadas para la expresión diaria. Fibras nobles y sastrería arquitectónica.',
    shopCollection: 'Comprar Colección',
    exploreArrivals: 'Explorar Novedades',
    scrollPrompt: 'Deslizar para Descubrir',
    signaturePillars: 'PILARES DISTINTIVOS',
    seasonalCurations: 'Selecciones de Temporada',
    explorePillar: 'Explorar',
    newReleases: 'NOVEDADES DE TEMPORADA',
    justArrived: 'Recién Llegado',
    viewAllNew: 'Ver Todas las Novedades',
    editorialTitle: 'EL ARTE DE LA MODERACIÓN Y DURABILIDAD',
    manifestoBtn: 'Leer Nuestra Historia',
    atelierParagraph1: 'Rechazamos las tendencias efímeras en favor de la pureza arquitectónica y el lujo táctil. Cada prenda comienza con la selección de fibras nobles.',
    atelierParagraph2: 'Nuestras siluetas están rigurosamente diseñadas para acompañar el movimiento natural del cuerpo con elegancia sin restricciones.',
    editionFabricFocus: 'Edición 04 • Fibras Nobles',
    curatedFavorites: 'Favoritos Seleccionados',
    trendingNow: 'TENDENCIAS',
    ethicallySourcedFibers: 'Fibras Naturales de Origen Ético',
    complimentaryExpressShipping: 'Envío Exprés Gratuito en pedidos superiores a ₹10,000',
    complimentary30DayReturns: 'Devoluciones Gratuitas en 30 Días',
    outerwearVaultTitle: 'ABRIGOS Y PARKAS',
    outerwearVaultSubtitle: 'Trenchs esculturales y abrigos de pura lana',
    fineCashmereTitle: 'PUNTO DE CASHMERE FINO',
    fineCashmereSubtitle: 'Cuellos mock y cárdigans en cashmere de Mongolia Grado A',
    relaxedTailoringTitle: 'SASTRERÍA RELAJADA',
    relaxedTailoringSubtitle: 'Blazers y pantalones plisados de lana tropical',
    collectionTitle: 'LA COLECCIÓN',
    refineCatalog: 'Filtros',
    searchProducts: 'Buscar Productos',
    categories: 'Categorías',
    allSilhouettes: 'Todas las Prendas',
    sizes: 'Tallas',
    palette: 'Colores',
    priceRange: 'Rango de Precios',
    inStockOnly: 'En Stock Únicamente',
    resetFilters: 'Restablecer Filtros',
    showing: 'Mostrando',
    pieces: 'Prendas',
    sortBy: 'Ordenar Por',
    featured: 'Destacados',
    newest: 'Más Recientes',
    priceLowHigh: 'Precio: Menor a Mayor',
    priceHighLow: 'Precio: Mayor a Menor',
    addToBag: 'Añadir a la Bolsa',
    addingToBag: 'Añadiendo...',
    soldOut: 'Agotado',
    quickAdd: 'Añadir Rápido',
    color: 'Color',
    selectSize: 'Seleccionar Talla',
    sizeGuide: 'Guía de Tallas',
    craftDetails: 'Confección y Detalles',
    materialsCare: 'Materiales y Cuidados',
    shippingReturns: 'Envíos y Devoluciones',
    complimentaryDelivery: 'Envío Exprés Gratuito',
    freeReturns: '30 Días de Devolución Gratuita',
    coordinatingPieces: 'Piezas Coordinadas',
    bagEmpty: 'Tu bolsa de compras está vacía',
    discoverCollection: 'Descubrir Colección',
    proceedCheckout: 'Proceder al Pago',
    viewShoppingBag: 'Ver Bolsa',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    shipping: 'Envío',
    totalDue: 'Total a Pagar',
    complimentary: 'GRATUITO',
    promoCode: 'Código de Descuento',
    apply: 'Aplicar',
    finalizeAcquisition: 'Pago Seguro',
    contactDetails: '1. Datos de Contacto',
    shippingAddress: '2. Dirección de Envío',
    paymentMethod: '3. Método de Pago',
    confirmAuthorize: 'Confirmar y Pagar',
    orderConfirmed: 'PEDIDO CONFIRMADO',
    thankYou: 'Gracias por tu compra. Estamos preparando tu envío.',
  },
  fr: {
    announcement: 'Livraison express offerte dès ₹10,000 d’achats • Code',
    languageName: 'Français',
    currency: 'INR (₹)',
    home: 'ACCUEIL',
    shopAll: 'BOUTIQUE',
    collections: 'COLLECTIONS',
    about: 'MAISON',
    search: 'Rechercher',
    bag: 'Panier',
    wishlist: 'Favoris',
    signIn: 'Connexion',
    register: 'Créer un Compte',
    account: 'Mon Compte',
    orderHistory: 'Historique des Commandes',
    savedPieces: 'Pièces Sauvegardées',
    signOut: 'Déconnexion',
    adminConsole: 'Console Administration',
    heroTag: 'COLLECTION N° 04 / ÉDITION 2026',
    heroTitle: 'DÉFINI PAR LE DESIGN',
    heroSubtitle: 'Essentiels contemporains conçus pour l’élégance quotidienne. Matières nobles et coupes architecturales.',
    shopCollection: 'Découvrir la Collection',
    exploreArrivals: 'Nouvelles Pièces',
    scrollPrompt: 'Défiler pour Découvrir',
    signaturePillars: 'PIÈCES EMBLÉMATIQUES',
    seasonalCurations: 'Sélections Saisonnières',
    explorePillar: 'Explorer',
    newReleases: 'NOUVEAUTÉS',
    justArrived: 'Derniers Arrivages',
    viewAllNew: 'Voir Tout',
    editorialTitle: 'L’ART DE LA RETENUE ET DE LA DURABILITÉ',
    manifestoBtn: 'Lire l’Histoire de la Maison',
    atelierParagraph1: 'Nous rejetons l’éphémère au profit de la pureté architecturale et du luxe tactile. Chaque création commence par la sélection rigoureuse de fibres nobles.',
    atelierParagraph2: 'Nos coupes accompagnent naturellement les mouvements du corps, offrant une distinction sans effort du matin jusqu’au soir.',
    editionFabricFocus: 'Édition 04 • Matières Nobles',
    curatedFavorites: 'Coups de Cœur',
    trendingNow: 'TENDANCES DU MOMENT',
    ethicallySourcedFibers: 'Fibres Naturelles Éco-responsables',
    complimentaryExpressShipping: 'Livraison Express Offerte dès ₹10,000',
    complimentary30DayReturns: 'Retours Offerts sous 30 Jours',
    outerwearVaultTitle: 'MANTEAUX & PIÈCES D’EXTÉRIEUR',
    outerwearVaultSubtitle: 'Trenchs sculpturaux et pardessus en pure laine',
    fineCashmereTitle: 'MAILLE EN CACHEMIRE FIN',
    fineCashmereSubtitle: 'Cols roulés et cardigans en cachemire de Mongolie Grade A',
    relaxedTailoringTitle: 'TAILLEUR DÉCONTRACTÉ',
    relaxedTailoringSubtitle: 'Blazers et pantalons à pinces en laine tropicale',
    collectionTitle: 'LA COLLECTION',
    refineCatalog: 'Filtres',
    searchProducts: 'Rechercher',
    categories: 'Catégories',
    allSilhouettes: 'Toutes les Silhouettes',
    sizes: 'Tailles',
    palette: 'Couleurs',
    priceRange: 'Prix',
    inStockOnly: 'En Stock Uniquement',
    resetFilters: 'Réinitialiser',
    showing: 'Affichage de',
    pieces: 'Pièces',
    sortBy: 'Trier Par',
    featured: 'Sélections En Vedette',
    newest: 'Plus Récents',
    priceLowHigh: 'Prix : Croissant',
    priceHighLow: 'Prix : Décroissant',
    addToBag: 'Ajouter au Panier',
    addingToBag: 'Ajout en cours...',
    soldOut: 'Épuisé',
    quickAdd: 'Ajout Rapide',
    color: 'Couleur',
    selectSize: 'Choisir la Taille',
    sizeGuide: 'Guide des Tailles',
    craftDetails: 'Façonnage & Détails',
    materialsCare: 'Matières & Entretien',
    shippingReturns: 'Livraison & Retours',
    complimentaryDelivery: 'Livraison Express Offerte',
    freeReturns: 'Retours Gratuits sous 30 Jours',
    coordinatingPieces: 'Pièces Coordonnées',
    bagEmpty: 'Votre panier est vide',
    discoverCollection: 'Découvrir la Collection',
    proceedCheckout: 'Commander',
    viewShoppingBag: 'Voir le Panier',
    subtotal: 'Sous-total',
    discount: 'Remise',
    shipping: 'Livraison',
    totalDue: 'Total',
    complimentary: 'OFFERT',
    promoCode: 'Code Promotionnel',
    apply: 'Appliquer',
    finalizeAcquisition: 'Paiement Sécurisé',
    contactDetails: '1. Coordonnées',
    shippingAddress: '2. Adresse de Livraison',
    paymentMethod: '3. Mode de Paiement',
    confirmAuthorize: 'Confirmer la Commande',
    orderConfirmed: 'COMMANDE CONFIRMÉE',
    thankYou: 'Merci pour votre confiance. Nous préparons votre colis avec soin.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('elane_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('elane_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
